name: OKAPI CI

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: lint tests
        run: |
          npm run ci
          npm run lint
      - name: unit tests
        run: npm test
        env:
          NODE_ENV: 'ci'
